services:
    redjan_ym_fcm.client:
        class: RedjanYm\FCMBundle\FCMClient
        public: true
        arguments: ['@sngrl.firebase_php_notification']

    sngrl.firebase_php_notification:
        class: sngrl\PhpFirebaseCloudMessaging\Client
        calls:
            - [setApiKey, ['%redjan_ym_fcm.firebase_api_key%']]
